language: python

python:
  - "3.6.5"
  - "3.5.2"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - py.test --cov=API


after_success:
- coveralls
